### ISSUE TITLE
User accounts support

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/Hexicord#13]
At current moment Hexicord doesn't seems to provide correct way to use selfbots. Providing such support can be a good idea.

### Semi-official rules for selfbots
* MFA Enabled account should get token from the Discord Client (localStorage.tokenin Console with Ctrl + Shift + I)
* If not MFA enabled, you can use /api/login to get the token, but it is strongly discouraged
* Be careful not to spam API due to bugs in your code as they're less forgiving for self bots
* Self bots should not act like actual bots
* Discord does not 'support' self bots.

See https://github.com/discordapp/discord-api-docs/issues/69.
Especially https://github.com/discordapp/discord-api-docs/issues/69#issuecomment-223886862 and https://github.com/discordapp/discord-api-docs/issues/69#issuecomment-223898291.

While following rules specified above, we can provide way to get user token using email/password pair for non-2FA accounts, and **we will not** provide way to perform 2FA auth.
It can be something like this:
```cpp
std::string userToken = Hexicord::Auth::passwordLogin("email@domain.com", "password");
```
Of course, there should be warning, see rule 2.
Any thoughts?

Also, as long as I know, there is also something called "Bearer" token, I'm not sure how it can be used, can somebody explain it to me?

**Comment by HexwellC** [comment]
self-bots are disallowed by Discord ToS if I'm not mistaking

**Comment by foxcpp** [comment]
>self-bots are disallowed by Discord ToS if I'm not mistaking

\- HexwellC

>We're not interested in banning self bots. Some users use them to do cool things. However, if your self bot does stupid stuff (like spams the API due to a bug in your code), we're much less forgiving than we would be if you were using a dedicated bot account.

\- jhgg (https://github.com/discordapp/discord-api-docs/issues/69#issuecomment-223898291)

And still, I can't see paragraph about selfbots in ToS

**Comment by HexwellC** [comment]
probs it got removed, my apologies

**Comment by foxcpp** [comment]
There will be no `passwordAuth`, Discord devs "hate" any automation of auth. All user accounts support we provide is argument `bool bot` in constructor.
